spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chronodb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      pool-name: chrono-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 5
      topic: helloworld.t1
    consumer:
      topic: helloworld.t2
      group-id: CCC
      enable-auto-commit: false


#channel:
#  kafka:
#    count: 2

ticker:
  process:
    repeat-time: 60000
    advance-time: 3000
  cache:
    repeat-time: 10000
