spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chronodb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      pool-name: chronograph-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 5
      topic: chronograph-out
    consumer:
      topic: chronograph-in
      group-id: chronograph-consumer-group
      enable-auto-commit: false

ticker:
  process:
    repeat-time: 60000
    advance-time: 3000
  cache:
    repeat-time: 10000

health:
  config:
    enabled: false

management:
  health:
    #    diskspace:
    #      enabled: true
    db:
      enabled: true
    #    refresh:
    #      enabled: false
    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always

  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"

#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full