spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chronodb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      pool-name: chronograph-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 5
      topic: chronograph-out
    consumer:
      topic: chronograph-in
      group-id: chronograph-consumer-group
      enable-auto-commit: false

ticker:
  process:
    repeat-time: 300000
    advance-time: 120000
  cache:
    repeat-time: 1000
